### PR TITLE
Add Chapter 02 - Linear Algebra Complete PyTorch Code

### PR DESCRIPTION
**Pull request by ishandutta0098**
Hi, I have made the following additions - 

1. Included 12 notebooks, one each for every topic in the chapter. These notebooks include the PyTorch implementation along with additional explanations and external resources.

2. Created a folder named `02-linear-algebra` and added the existing notebook to it as well to keep things organized. moving ahead I will follow the same naming convention to add the next chapters in PyTorch, already in the process of preparing the notebooks.

3. Added a .gitignore file to prevent pycache and ipynb checkpoints from being committed.

### CODE REVIEW

**Comment by ishandutta0098** [comment]
Hi, @init27 please merge the PR, I am working on the other chapters as well and would like to keep separate PRs for each chapter.

**Comment by init27** [comment]
Hi @ishandutta0098 Thank you very much for the PR! 

I'd like to discuss the arrangement of notebooks: Is there a reason for prefering multiple Torch notebooks instead of one? My preference would be to have all of them under one single notebook so that it's less daunting to someone working their view through the notebooks.
Also, since the concepts are quite small, we could have all of them under the same shell. 

Happy to discuss/hear your thoughts. 

Thanks!

**Comment by ishandutta0098** [comment]
Hi, @init27 I created separate notebooks for 2 reasons -

1. A single notebook would have been too long and difficult to navigate. 
2. It will be easier for people to add more examples/explanations to these notebooks with their PRs.

But I understand the intent behind a single notebook. Let me know if you would want it to be in a single notebook I will do the same.

**Comment by init27** [comment]
@ishandutta0098 Apologies, I was on the road last week. 

If this is still of interest to you- I think a single notebook might be perfect. My stance is multiple notebooks might be difficult to navigate among everything. 

Happy to merge what you think would be best :)

**Comment by ishandutta0098** [comment]
Hi, @init27 I closed this PR because I wanted to create a new one with the single notebook version. I will add it after being combined with a new PR.

**Comment by init27** [comment]
Makes sense, Looking forward to it! 
Thank you!

**Pull request closed without merging**
